version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend/event-search:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    restart: unless-stopped
